lod> misc.lod bb.lod bb2.lod bb3.lod bb4.lod bb5.lod bb6.lod bb7.lod
lod> bbmug.lod bbpal.lod

asm> ndsp1.asm main.asm util.asm pal.asm mproc.asm
asm> bakgnd.asm bgndtbl.asm bgndpal.asm imgtbl.asm imgpal.asm
asm> bb.asm bb3.asm plyr.asm plyr2.asm plyrat.asm plyrseq.asm plyrdseq.asm
asm> plyrseq2.asm score.asm score2.asm bb2.asm bb4.asm
asm> drone.asm drone2.asm
asm> sounds.asm patch.asm text.asm plyr3.asm
asm> plyrat2.asm plyrlseq.asm plyrrseq.asm
asm> attract.asm plyrstnd.asm select.asm
asm> select2.asm string.asm record.asm speech.asm
asm> adjust.asm audit.asm test.asm diag.asm menu.asm hstd.asm
asm> makeplr.asm makeplr2.asm screen.asm select3.asm select4.asm plyrat3.asm
asm> plyrdsq2.asm
